import Head from "next/head";
import { KittyForm } from "~/components/kitty/KittyForm";

export default function SimpleExample() {

  return (
    <>
      <Head>
        <title>Applicación</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-start">
        <KittyForm />
      </main>
    </>
  );
}
